import type { Config } from "../config.js";
import type { ProjectContext } from "../context/builder.js";
import type { PullRequestData } from "../github/pullRequest.js";
import type { PromptDiff, BatchDiff } from "./diff.js";

// ── XML escaping ──────────────────────────────────────────────────────────────

/**
 * Escape XML special characters to prevent user content from breaking out of
 * XML sandbox tags.
 */
export function escapeXml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

// ── Output schema instructions ────────────────────────────────────────────────

export function outputInstructions(
  forAllFiles: boolean,
  suggestionsEnabled: boolean,
  maxCommentChars: number,
): string {
  const filesSummaryInstruction = forAllFiles
    ? "Include one entry in filesSummary for every changed file."
    : "Include one entry in filesSummary for every file whose diff appears above. " +
      "Do NOT invent descriptions for files not shown in the diff.";

  const suggestionField = suggestionsEnabled
    ? `\n      "suggestion": "corrected code (new lines only) — omit if no concrete replacement"`
    : "";

  return `
Respond with a single JSON object and nothing else (no markdown fences). Shape:
{
  "prSummary": "string — short neutral description of what this PR does (round 1 only; empty string in round 2)",
  "summary": "string — overall assessment, 1-4 sentences",
  "action": "APPROVE|REQUEST_CHANGES|COMMENT",   // your recommendation to human reviewers
  "filesSummary": [
    {
      "path": "repo-relative file path",
      "description": "one-line description of what changed in this file (≤100 chars)"
    }
  ],
  "comments": [
    {
      "path": "repo-relative file path",
      "line": 123,                        // line in the NEW file (the '+' side of the diff)
      "severity": "blocker|warning",
      "body": "markdown comment about this specific line (≤${maxCommentChars} chars)"${suggestionField}
    }
  ]
}

${
  suggestionsEnabled
    ? `Suggestion rules:
- Include "suggestion" only when you have a concrete code replacement.
- Write ONLY the new lines. Do not repeat old lines, do not use diff syntax
  (no +/-, no @@ headers), do not wrap in code fences.
- For single-line fixes: a single string like "return items.filter(Boolean);"
- For multi-line fixes: use \\n within the string for newlines.
- If you are not sure about the exact replacement, omit "suggestion".

`
    : ""
}action rules (your recommendation to human reviewers — you do not block or approve merges):
  APPROVE          — no issues found; you recommend merging.
  REQUEST_CHANGES  — blocker-severity issues found; you recommend addressing them first.
  COMMENT          — warnings or observations only; author decides.

${filesSummaryInstruction}
Only comment on lines that appear in the diff. If there is nothing to flag,
return an empty "comments" array and say so in the summary.`;
}

// ── Public API ────────────────────────────────────────────────────────────────

export function buildSystemPrompt(config: Config): string {
  return config.preprompt.trim();
}

export interface UserPromptOpts {
  /** 1 = first review, 2 = final review. Defaults to 1. */
  round?: number;
  /** Formatted PR discussion text, injected on round 2. */
  discussion?: string;
  /** Persistent per-repo memory generated by repoMemory.ts. */
  repoMemory?: string;
  /**
   * Rendered review history (past PR outcomes) from reviewHistory.ts.
   * Injected after repo memory so the reviewer can spot recurring issues
   * and avoid re-flagging patterns that were previously dismissed.
   */
  reviewHistory?: string;
  /**
   * Merged org + repo instructions from .zanuda/instructions.md.
   * Written by maintainers on the base branch — intentionally injected
   * without XML sandboxing so the model treats them as reviewer guidelines.
   * (Contrast with PR-author content which IS sandboxed.)
   */
  instructions?: string;
  /**
   * Structured diff assembled by buildPromptDiff().
   * When provided, replaces the raw pr.diff truncation approach — gives the
   * model complete per-file diffs rather than an arbitrary byte-truncated blob.
   */
  promptDiff?: PromptDiff;
  /**
   * When true the output JSON schema description is omitted from the prompt —
   * the schema is enforced at the API level via jsonSchema / tool_use instead.
   * Saves ~150 tokens per review.
   */
  structuredOutput?: boolean;
}

export function buildUserPrompt(
  pr: PullRequestData,
  context: ProjectContext,
  config: Config,
  opts: UserPromptOpts = {},
): string {
  const { round = 1, discussion } = opts;
  const isFinal = round >= 2;

  // Use the structured per-file diff when available; fall back to the raw diff
  // truncation for connectors that don't supply per-file patches.
  const diffSection = opts.promptDiff
    ? buildDiffSection(opts.promptDiff, pr.changedFiles.length)
    : buildFallbackDiffSection(pr.diff, config.review.maxDiffChars);

  const parts: string[] = [];

  if (opts.repoMemory) {
    parts.push(
      "## Repo memory (persistent knowledge about this codebase)",
      "<repo_memory>",
      escapeXml(opts.repoMemory),
      "</repo_memory>",
      "",
    );
  }

  if (opts.reviewHistory) {
    // Trusted internal data — not XML-sandboxed.
    parts.push(opts.reviewHistory, "");
  }

  if (opts.instructions) {
    // Not XML-sandboxed: this content is from .zanuda/instructions.md on the
    // base branch, written by repo maintainers. We want the model to follow
    // these guidelines — sandboxing would tell it to ignore them.
    parts.push(
      "## Repo-specific reviewer guidelines (.zanuda/instructions.md)",
      opts.instructions.trim(),
      "",
    );
  }

  parts.push(
    "## Project context",
    context.text,
    "",
    // PR title/body are user-controlled — wrapped in XML tags so the model
    // can clearly distinguish them from trusted instructions.
    `## Pull request${isFinal ? " (round 2 of 2 — FINAL)" : ""}`,
    `<pr_title>${escapeXml(pr.title)}</pr_title>`,
    pr.body
      ? `<pr_description>\n${escapeXml(pr.body)}\n</pr_description>`
      : "<pr_description>(none)</pr_description>",
    `Changed files (${pr.changedFiles.length}):`,
    pr.changedFiles.map((f) => `- ${f}`).join("\n"),
    "",
  );

  if (isFinal && discussion) {
    parts.push(
      "## Discussion since round 1",
      // Wrap in XML — discussion contains user-controlled comment bodies and
      // must not be mistaken for trusted instructions by the model.
      "<discussion>",
      escapeXml(discussion),
      "</discussion>",
      "",
    );
  }

  parts.push(
    ...diffSection.parts,
    "",
    isFinal
      ? finalTaskInstructions(
          diffSection.forAllFiles,
          opts.structuredOutput,
          config.review.suggestions,
          config.review.maxCommentChars,
        )
      : round1TaskInstructions(
          diffSection.forAllFiles,
          opts.structuredOutput,
          config.review.suggestions,
          config.review.maxCommentChars,
        ),
  );

  return parts.join("\n");
}

// ── Diff section builders ─────────────────────────────────────────────────────

interface DiffSection {
  parts: string[];
  forAllFiles: boolean;
}

function buildDiffSection(diff: PromptDiff, totalFiles: number): DiffSection {
  const includedCount = diff.includedFiles.length;
  const excludedCount = diff.excludedFiles.length;
  const forAllFiles = !diff.truncated;

  const parts: string[] = ["## Current diff"];

  if (diff.truncated) {
    parts.push(
      `> ⚠️ **Large PR** — showing ${includedCount} of ${totalFiles} files ` +
        `(largest changes first). The following ${excludedCount} file(s) are not shown:`,
      diff.excludedFiles
        .filter((f) => f.patch !== undefined)
        .map((f) => `> - \`${f.filename}\` (+${f.additions}/-${f.deletions})`)
        .join("\n"),
      "",
    );

    const noPatch = diff.excludedFiles.filter((f) => f.patch === undefined);
    if (noPatch.length > 0) {
      parts.push(
        `> ${noPatch.length} additional file(s) have no inline diff available ` +
          `(binary or too large for the platform to inline):`,
        noPatch.map((f) => `> - \`${f.filename}\``).join("\n"),
        "",
      );
    }
  }

  parts.push("```diff", diff.text || "(empty diff)", "```");

  return { parts, forAllFiles };
}

function buildFallbackDiffSection(
  rawDiff: string,
  maxChars: number,
): DiffSection {
  const result = truncate(rawDiff, maxChars);
  const parts = [
    "## Current diff",
    "```diff",
    result.text,
    "```",
    result.truncated ? "\n(Diff truncated due to size.)" : "",
  ];
  return { parts, forAllFiles: !result.truncated };
}

// ── Task instructions ─────────────────────────────────────────────────────────

function round1TaskInstructions(
  forAllFiles: boolean,
  structured = false,
  suggestions = false,
  maxCommentChars = 400,
): string {
  return (
    `## Your task\n` +
    `Review the diff above using the project context and your instructions.\n\n` +
    `Also fill in \`prSummary\`: 1\u20133 sentences describing what this PR does in plain English — ` +
    `not a review, just a neutral description of the change from the author's perspective. ` +
    `Derive it from the diff, PR title, and description.\n` +
    (structured
      ? ""
      : outputInstructions(forAllFiles, suggestions, maxCommentChars))
  );
}

function finalTaskInstructions(
  forAllFiles: boolean,
  structured = false,
  suggestions = false,
  maxCommentChars = 400,
): string {
  return (
    `## Your task (FINAL — round 2 of 2)\n` +
    `\n` +
    `This is NOT a new review. You already reviewed this PR in round 1 (see the\n` +
    `Discussion below). Your sole job now: follow up on your own findings.\n` +
    `\n` +
    `Structure your summary as a status update:\n` +
    `1. **Round-1 follow-up:** go through each issue you flagged in round 1. For each:\n` +
    `   - State whether the author addressed it (addressed / partially addressed / not addressed)\n` +
    `   - If partially or not addressed: what still needs fixing\n` +
    `2. **New findings:** only flag NEW blockers introduced by the author's fixes.\n` +
    `   Do NOT re-flag things you already covered in step 1.\n` +
    `\n` +
    `Valid actions for round 2:\n` +
    `  APPROVE          — all round-1 issues resolved; no new blockers.\n` +
    `  REQUEST_CHANGES  — unresolved round-1 blockers remain, or new blockers.\n` +
    `  COMMENT          — warnings only; no blockers old or new.\n` +
    `\n` +
    `CRITICAL:\n` +
    `- prSummary MUST be an empty string. Do NOT describe what the PR does.\n` +
    `- Your summary must read like a follow-up status check on round 1. If it\n` +
    `  could pass as a standalone round-1 review of the whole PR, redo it.\n` +
    (structured
      ? ""
      : outputInstructions(forAllFiles, suggestions, maxCommentChars))
  );
}

// ── truncate (kept for fallback path and tests) ───────────────────────────────

/**
 * Truncate `s` to at most `max` characters, cutting at the last newline
 * before the limit so the model never receives a half-line of diff.
 */
export function truncate(
  s: string,
  max: number,
): { text: string; truncated: boolean } {
  if (s.length <= max) return { text: s, truncated: false };
  const cut = s.lastIndexOf("\n", max - 1);
  // Fall back to a hard character cut if there's no newline before the limit
  // (e.g. a single huge line).
  const end = cut > 0 ? cut : max;
  return { text: s.slice(0, end), truncated: true };
}

// ── Batch review prompt ──────────────────────────────────────────────────────

export interface BatchPromptOpts {
  /** The batch being reviewed (1-indexed). */
  batchIndex: number;
  /** Total number of batches. */
  totalBatches: number;
  /** Accumulated findings from all previous batches (empty for batch 1). */
  runningSummary?: string;
  /** Round number (1 or 2). */
  round?: number;
  /** PR discussion, injected on round 2. */
  discussion?: string;
  repoMemory?: string;
  reviewHistory?: string;
  instructions?: string;
  structuredOutput?: boolean;
  /** True if this is the final batch (last in the sequence). */
  isLastBatch: boolean;
}

/**
 * Build the user prompt for a single batch in a multi-batch sequential review.
 *
 * Each batch prompt:
 *   - Includes the shared context (repo memory, review history, instructions)
 *   - Includes the running summary from previous batches (except batch 1)
 *   - Includes the batch diff with file headers
 *   - Gives batch-specific task instructions: review only these files,
 *     produce comments + a findings summary for the next batch
 *
 * The final batch also gets the overall verdict task.
 */
export function buildBatchUserPrompt(
  pr: PullRequestData,
  context: ProjectContext,
  config: Config,
  batch: BatchDiff,
  opts: BatchPromptOpts,
): string {
  const round = opts.round ?? 1;
  const isFinalRound = round >= 2;

  const parts: string[] = [];

  if (opts.repoMemory) {
    parts.push(
      "## Repo memory (persistent knowledge about this codebase)",
      "<repo_memory>",
      escapeXml(opts.repoMemory),
      "</repo_memory>",
      "",
    );
  }

  if (opts.reviewHistory) {
    parts.push(opts.reviewHistory, "");
  }

  if (opts.instructions) {
    parts.push(
      "## Repo-specific reviewer guidelines (.zanuda/instructions.md)",
      opts.instructions.trim(),
      "",
    );
  }

  parts.push(
    "## Project context",
    context.text,
    "",
    `## Pull request${isFinalRound ? " (round 2 of 2 — FINAL)" : ""}`,
    `<pr_title>${escapeXml(pr.title)}</pr_title>`,
    pr.body
      ? `<pr_description>\n${escapeXml(pr.body)}\n</pr_description>`
      : "<pr_description>(none)</pr_description>",
    `Changed files (${pr.changedFiles.length}):`,
    pr.changedFiles.map((f) => `- ${f}`).join("\n"),
    "",
  );

  if (isFinalRound && opts.discussion) {
    parts.push(
      "## Discussion since round 1",
      "<discussion>",
      escapeXml(opts.discussion),
      "</discussion>",
      "",
    );
  }

  // Batch header (no running summary — each batch is independent)
  const batchLabel = opts.isLastBatch
    ? `Batch ${opts.batchIndex} of ${opts.totalBatches} (FINAL BATCH)`
    : `Batch ${opts.batchIndex} of ${opts.totalBatches}`;

  parts.push(
    `## ${batchLabel} — review these files\n`,
    `Files in this batch: ${batch.files.map((f) => `\`${f.filename}\``).join(", ")}`,
    "",
    batch.text,
    "",
    batchTaskInstructions(opts),
  );

  return parts.join("\n");
}

function batchTaskInstructions(opts: BatchPromptOpts): string {
  const { batchIndex, totalBatches, isLastBatch, structuredOutput } = opts;

  if (isLastBatch) {
    return (
      `## Your task (batch ${batchIndex} of ${totalBatches} — FINAL)\n` +
      `Review the files above. This is the last batch in a multi-batch review.\n\n` +
      `Produce the FINAL review output:\n` +
      `- Inline comments for issues in this batch's files\n` +
      `- A final \`action\` verdict that considers whether ANY batch above\n` +
      `  found blockers (check the progress status in the system prompt)\n` +
      `- A \`summary\` that covers the full PR, not just this batch\n` +
      `- \`prSummary\` describing what the whole PR does\n` +
      (structuredOutput ? "" : outputInstructions(true, false, 400)) // structured output handled at API level
    );
  }

  return (
    `## Your task (batch ${batchIndex} of ${totalBatches})\n` +
    `Review ONLY the files in this batch. You are reviewing in isolation.\n` +
    `If you notice something that depends on files in other batches you\n` +
    `cannot see, do not flag it — you cannot verify it.\n\n` +
    `Produce:\n` +
    `- Inline comments for issues you can verify in these files\n` +
    `- Set \`filesSummary\` for the files in this batch only\n` +
    `- Set \`action\` to COMMENT (the final batch produces the verdict)\n\n` +
    (structuredOutput ? "" : batchOutputInstructions())
  );
}

function batchOutputInstructions(): string {
  return `
Respond with a single JSON object and nothing else (no markdown fences). Shape:
{
  "prSummary": "string — empty for intermediate batches",
  "summary": "string — overall assessment for this batch",
  "action": "COMMENT",
  "filesSummary": [
    {
      "path": "repo-relative file path",
      "description": "one-line description of what changed in this file (≤100 chars)"
    }
  ],
  "comments": [
    {
      "path": "repo-relative file path",
      "line": 123,
      "severity": "blocker|warning",
      "body": "markdown comment about this specific line (≤400 chars)"
    }
  ]
}

Only comment on lines that appear in the diff for this batch.
If there is nothing to flag, return an empty "comments" array.`;
}
