import type { Config } from "../config.js";
import type { ProjectContext } from "../context/builder.js";
import type { PullRequestData } from "../github/pullRequest.js";
import type { PromptDiff } from "./diff.js";

// ── XML escaping ──────────────────────────────────────────────────────────────

/**
 * Escape XML special characters to prevent user content from breaking out of
 * XML sandbox tags.
 */
export function escapeXml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

// ── Output schema instructions ────────────────────────────────────────────────

function outputInstructions(forAllFiles: boolean): string {
  const filesSummaryInstruction = forAllFiles
    ? "Include one entry in filesSummary for every changed file."
    : "Include one entry in filesSummary for every file whose diff appears above. " +
      "Do NOT invent descriptions for files not shown in the diff.";

  return `
Respond with a single JSON object and nothing else (no markdown fences). Shape:
{
  "prSummary": "string — short neutral description of what this PR does (round 1 only; empty string in round 2)",
  "summary": "string — overall assessment, 1-4 sentences",
  "action": "APPROVE|REQUEST_CHANGES|COMMENT",   // your recommendation to human reviewers
  "filesSummary": [
    {
      "path": "repo-relative file path",
      "description": "one-line description of what changed in this file"
    }
  ],
  "comments": [
    {
      "path": "repo-relative file path",
      "line": 123,                        // line in the NEW file (the '+' side of the diff)
      "severity": "blocker|warning",
      "body": "markdown comment about this specific line (≤400 chars)"
    }
  ]
}

action rules (your recommendation to human reviewers — you do not block or approve merges):
  APPROVE          — no issues found; you recommend merging.
  REQUEST_CHANGES  — blocker-severity issues found; you recommend addressing them first.
  COMMENT          — warnings or observations only; author decides.

${filesSummaryInstruction}
Only comment on lines that appear in the diff. If there is nothing to flag,
return an empty "comments" array and say so in the summary.`;
}

// ── Public API ────────────────────────────────────────────────────────────────

export function buildSystemPrompt(config: Config): string {
  return config.preprompt.trim();
}

export interface UserPromptOpts {
  /** 1 = first review, 2 = final review. Defaults to 1. */
  round?: number;
  /** Formatted PR discussion text, injected on round 2. */
  discussion?: string;
  /** Persistent per-repo memory generated by repoMemory.ts. */
  repoMemory?: string;
  /**
   * Rendered review history (past PR outcomes) from reviewHistory.ts.
   * Injected after repo memory so the reviewer can spot recurring issues
   * and avoid re-flagging patterns that were previously dismissed.
   */
  reviewHistory?: string;
  /**
   * Merged org + repo instructions from .zanuda/instructions.md.
   * Written by maintainers on the base branch — intentionally injected
   * without XML sandboxing so the model treats them as reviewer guidelines.
   * (Contrast with PR-author content which IS sandboxed.)
   */
  instructions?: string;
  /**
   * Structured diff assembled by buildPromptDiff().
   * When provided, replaces the raw pr.diff truncation approach — gives the
   * model complete per-file diffs rather than an arbitrary byte-truncated blob.
   */
  promptDiff?: PromptDiff;
  /**
   * When true the output JSON schema description is omitted from the prompt —
   * the schema is enforced at the API level via jsonSchema / tool_use instead.
   * Saves ~150 tokens per review.
   */
  structuredOutput?: boolean;
}

export function buildUserPrompt(
  pr: PullRequestData,
  context: ProjectContext,
  config: Config,
  opts: UserPromptOpts = {},
): string {
  const { round = 1, discussion } = opts;
  const isFinal = round >= 2;

  // Use the structured per-file diff when available; fall back to the raw diff
  // truncation for connectors that don't supply per-file patches.
  const diffSection = opts.promptDiff
    ? buildDiffSection(opts.promptDiff, pr.changedFiles.length)
    : buildFallbackDiffSection(pr.diff, config.review.maxDiffChars);

  const parts: string[] = [];

  if (opts.repoMemory) {
    parts.push(
      "## Repo memory (persistent knowledge about this codebase)",
      "<repo_memory>",
      escapeXml(opts.repoMemory),
      "</repo_memory>",
      "",
    );
  }

  if (opts.reviewHistory) {
    // Trusted internal data — not XML-sandboxed.
    parts.push(opts.reviewHistory, "");
  }

  if (opts.instructions) {
    // Not XML-sandboxed: this content is from .zanuda/instructions.md on the
    // base branch, written by repo maintainers. We want the model to follow
    // these guidelines — sandboxing would tell it to ignore them.
    parts.push(
      "## Repo-specific reviewer guidelines (.zanuda/instructions.md)",
      opts.instructions.trim(),
      "",
    );
  }

  parts.push(
    "## Project context",
    context.text,
    "",
    // PR title/body are user-controlled — wrapped in XML tags so the model
    // can clearly distinguish them from trusted instructions.
    `## Pull request${isFinal ? " (round 2 of 2 — FINAL)" : ""}`,
    `<pr_title>${escapeXml(pr.title)}</pr_title>`,
    pr.body
      ? `<pr_description>\n${escapeXml(pr.body)}\n</pr_description>`
      : "<pr_description>(none)</pr_description>",
    `Changed files (${pr.changedFiles.length}):`,
    pr.changedFiles.map((f) => `- ${f}`).join("\n"),
    "",
  );

  if (isFinal && discussion) {
    parts.push(
      "## Discussion since round 1",
      // Wrap in XML — discussion contains user-controlled comment bodies and
      // must not be mistaken for trusted instructions by the model.
      "<discussion>",
      escapeXml(discussion),
      "</discussion>",
      "",
    );
  }

  parts.push(
    ...diffSection.parts,
    "",
    isFinal
      ? finalTaskInstructions(diffSection.forAllFiles, opts.structuredOutput)
      : round1TaskInstructions(diffSection.forAllFiles, opts.structuredOutput),
  );

  return parts.join("\n");
}

// ── Diff section builders ─────────────────────────────────────────────────────

interface DiffSection {
  parts: string[];
  forAllFiles: boolean;
}

function buildDiffSection(diff: PromptDiff, totalFiles: number): DiffSection {
  const includedCount = diff.includedFiles.length;
  const excludedCount = diff.excludedFiles.length;
  const forAllFiles = !diff.truncated;

  const parts: string[] = ["## Current diff"];

  if (diff.truncated) {
    parts.push(
      `> ⚠️ **Large PR** — showing ${includedCount} of ${totalFiles} files ` +
        `(largest changes first). The following ${excludedCount} file(s) are not shown:`,
      diff.excludedFiles
        .filter((f) => f.patch !== undefined)
        .map((f) => `> - \`${f.filename}\` (+${f.additions}/-${f.deletions})`)
        .join("\n"),
      "",
    );

    const noPatch = diff.excludedFiles.filter((f) => f.patch === undefined);
    if (noPatch.length > 0) {
      parts.push(
        `> ${noPatch.length} additional file(s) have no inline diff available ` +
          `(binary or too large for the platform to inline):`,
        noPatch.map((f) => `> - \`${f.filename}\``).join("\n"),
        "",
      );
    }
  }

  parts.push("```diff", diff.text || "(empty diff)", "```");

  return { parts, forAllFiles };
}

function buildFallbackDiffSection(
  rawDiff: string,
  maxChars: number,
): DiffSection {
  const result = truncate(rawDiff, maxChars);
  const parts = [
    "## Current diff",
    "```diff",
    result.text,
    "```",
    result.truncated ? "\n(Diff truncated due to size.)" : "",
  ];
  return { parts, forAllFiles: !result.truncated };
}

// ── Task instructions ─────────────────────────────────────────────────────────

function round1TaskInstructions(
  forAllFiles: boolean,
  structured = false,
): string {
  return (
    `## Your task\n` +
    `Review the diff above using the project context and your instructions.\n\n` +
    `Also fill in \`prSummary\`: 1\u20133 sentences describing what this PR does in plain English — ` +
    `not a review, just a neutral description of the change from the author's perspective. ` +
    `Derive it from the diff, PR title, and description.\n` +
    (structured ? "" : outputInstructions(forAllFiles))
  );
}

function finalTaskInstructions(
  forAllFiles: boolean,
  structured = false,
): string {
  return (
    `## Your task (FINAL — round 2 of 2)\n` +
    `Examine the current diff and the discussion above. Assess whether the issues ` +
    `from round 1 have been adequately addressed. This is your last word on this PR.\n\n` +
    `Valid actions for round 2:\n` +
    `  APPROVE          — issues resolved; you recommend merging.\n` +
    `  REQUEST_CHANGES  — unresolved blockers remain; you recommend not merging yet.\n` +
    `  COMMENT          — observations only or minor issues; author decides.\n\n` +
    `When using REQUEST_CHANGES or COMMENT, your summary must clearly state what\n` +
    `still needs fixing and why. Be specific and direct.\n\n` +
    `Set \`prSummary\` to an empty string — it is not needed for round 2.\n` +
    (structured ? "" : outputInstructions(forAllFiles))
  );
}

// ── truncate (kept for fallback path and tests) ───────────────────────────────

/**
 * Truncate `s` to at most `max` characters, cutting at the last newline
 * before the limit so the model never receives a half-line of diff.
 */
export function truncate(
  s: string,
  max: number,
): { text: string; truncated: boolean } {
  if (s.length <= max) return { text: s, truncated: false };
  const cut = s.lastIndexOf("\n", max - 1);
  // Fall back to a hard character cut if there's no newline before the limit
  // (e.g. a single huge line).
  const end = cut > 0 ? cut : max;
  return { text: s.slice(0, end), truncated: true };
}
