import type { Config } from "../config.js";
import type { ProjectContext } from "../context/builder.js";
import type { PullRequestData } from "../github/pullRequest.js";

/** The JSON contract we instruct the model to follow. */
const OUTPUT_INSTRUCTIONS = `
Respond with a single JSON object and nothing else (no markdown fences). Shape:
{
  "summary": "string — overall assessment, 1-4 sentences",
  "action": "APPROVE|REQUEST_CHANGES|COMMENT",
  "filesSummary": [
    {
      "path": "repo-relative file path",
      "description": "one-line description of what changed in this file"
    }
  ],
  "comments": [
    {
      "path": "repo-relative file path",
      "line": 123,                        // line in the NEW file (the '+' side of the diff)
      "severity": "blocker|warning|praise",
      "body": "markdown comment about this specific line"
    }
  ]
}

action rules:
  APPROVE          — no blockers, no warnings; the code is solid and safe to merge.
  REQUEST_CHANGES  — one or more blocker-severity issues; must not merge as-is.
  COMMENT          — warnings or observations only; author can decide whether to act.

Include one entry in filesSummary for every changed file.
Only comment on lines that appear in the diff. If there is nothing to flag,
return an empty "comments" array and say so in the summary.`;

export function buildSystemPrompt(config: Config): string {
  return config.preprompt.trim();
}

export interface UserPromptOpts {
  /** 1 = first review, 2 = final review. Defaults to 1. */
  round?: number;
  /** Formatted PR discussion text, injected on round 2. */
  discussion?: string;
  /** Persistent per-repo memory generated by repoMemory.ts. */
  repoMemory?: string;
  /**
   * Merged org + repo instructions from .zanuda/instructions.md.
   * Written by maintainers on the base branch — intentionally injected
   * without XML sandboxing so the model treats them as reviewer guidelines.
   * (Contrast with PR-author content which IS sandboxed.)
   */
  instructions?: string;
}

export function buildUserPrompt(
  pr: PullRequestData,
  context: ProjectContext,
  config: Config,
  opts: UserPromptOpts = {},
): string {
  const { round = 1, discussion } = opts;
  const diff = truncate(pr.diff, config.review.maxDiffChars);
  const isFinal = round >= 2;

  const parts: string[] = [];

  if (opts.repoMemory) {
    parts.push(
      "## Repo memory (persistent knowledge about this codebase)",
      "<repo_memory>",
      opts.repoMemory,
      "</repo_memory>",
      "",
    );
  }

  if (opts.instructions) {
    // Not XML-sandboxed: this content is from .zanuda/instructions.md on the
    // base branch, written by repo maintainers. We want the model to follow
    // these guidelines — sandboxing would tell it to ignore them.
    parts.push(
      "## Repo-specific reviewer guidelines (.zanuda/instructions.md)",
      opts.instructions.trim(),
      "",
    );
  }

  parts.push(
    "## Project context",
    context.text,
    "",
    // PR title/body are user-controlled — wrapped in XML tags so the model
    // can clearly distinguish them from trusted instructions.
    `## Pull request${isFinal ? " (round 2 of 2 — FINAL)" : ""}`,
    `<pr_title>${pr.title}</pr_title>`,
    pr.body
      ? `<pr_description>\n${pr.body}\n</pr_description>`
      : "<pr_description>(none)</pr_description>",
    `Changed files (${pr.changedFiles.length}):`,
    pr.changedFiles.map((f) => `- ${f}`).join("\n"),
    "",
  );

  if (isFinal && discussion) {
    parts.push(
      "## Discussion since round 1",
      // Wrap in XML — discussion contains user-controlled comment bodies and
      // must not be mistaken for trusted instructions by the model.
      "<discussion>",
      discussion,
      "</discussion>",
      "",
    );
  }

  parts.push(
    "## Current diff",
    "```diff",
    diff.text,
    "```",
    diff.truncated ? "\n(Diff truncated due to size.)" : "",
    "",
    isFinal ? FINAL_TASK_INSTRUCTIONS : ROUND1_TASK_INSTRUCTIONS,
  );

  return parts.join("\n");
}

const ROUND1_TASK_INSTRUCTIONS =
  `## Your task\nReview the diff above using the project context and your instructions.\n` +
  OUTPUT_INSTRUCTIONS;

const FINAL_TASK_INSTRUCTIONS =
  `## Your task (FINAL — round 2 of 2)\n` +
  `Examine the current diff and the discussion above. Assess whether the issues ` +
  `from round 1 have been adequately addressed. This is your last word on this PR.\n\n` +
  `Valid actions for round 2:\n` +
  `  APPROVE — issues resolved; PR is safe to merge.\n` +
  `  COMMENT — issues remain that were NOT adequately addressed. When using COMMENT,\n` +
  `            your summary MUST explicitly state the PR is not ready to merge and\n` +
  `            list what still needs fixing. Be specific and direct.\n\n` +
  `Do NOT use REQUEST_CHANGES — this is the final round and you cannot follow up,\n` +
  `so blocking the PR would leave it stuck permanently.\n` +
  OUTPUT_INSTRUCTIONS;

/**
 * Truncate `s` to at most `max` characters, cutting at the last newline
 * before the limit so the model never receives a half-line of diff.
 */
export function truncate(s: string, max: number): { text: string; truncated: boolean } {
  if (s.length <= max) return { text: s, truncated: false };
  const cut = s.lastIndexOf("\n", max - 1);
  // Fall back to a hard character cut if there's no newline before the limit
  // (e.g. a single huge line).
  const end = cut > 0 ? cut : max;
  return { text: s.slice(0, end), truncated: true };
}
